name: on-main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  create-github-runner:
    name: Create GitHub Runner
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform test
        run: terraform apply --auto-approve -var github_access_token=${{ secrets.PAT }} -var github_commit_sha=${{ github.sha }} -var vpc_id=${{ secrets.VPC_ID }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: create-github-runner
    steps:
      - run: echo Works!
