name: on-main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  #------------------------------------------------------------------------------
  # DEV
  #------------------------------------------------------------------------------
  create-github-runner-dev:
    name: Create GitHub Runner (dev)
    runs-on: ubuntu-latest
    environment: test
    concurrency:
      group: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Set Outputs
        id: vars
        run: |
          echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
        env:
          ENVIRONMENT: dev

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Run Terraform Init
        run: terraform init

      - name: Run Terraform Apply
        run: terraform apply --auto-approve -var github_access_token=${{ secrets.PAT }} -var github_commit_sha=${{ steps.vars.outputs.SHA_SHORT }} -var vpc_id=${{ secrets.VPC_ID }}

      - uses: actions/upload-artifact@v4
        with:
          name: terraform-dev.tfstate
          path: terraform.tfstate

  deploy-dev:
    name: Deploy (dev)
    runs-on: self-hosted
    needs: create-github-runner-dev
    environment: test
    steps:
      - run: echo Works!

  remove-github-runner-dev:
    name: Remove GitHub Runner (dev)
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Set ECS Task Count To 0 # The container removes the GitHub Runner when stopped. Terraform Destroy does not stop the container, it just deletes it
        run: aws ecs update-service --cluster github-runner-${{ needs.create-github-runner-dev.outputs.SHA_SHORT }} --service github-runner-${{ needs.create-github-runner-dev.outputs.SHA_SHORT }} --desired-count 0

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Run Terraform init
        run: terraform init

      - uses: actions/download-artifact@v4
        with:
          name: terraform-dev.tfstate

      - name: Run Terraform Destroy
        run: terraform destroy --auto-approve -var github_access_token=${{ secrets.PAT }} -var github_commit_sha=${{ needs.create-github-runner-dev.outputs.SHA_SHORT }} -var vpc_id=${{ secrets.VPC_ID }}

  #------------------------------------------------------------------------------
  # TEST
  #------------------------------------------------------------------------------
