name: on-main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  create-github-runner:
    name: Create GitHub Runner
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Set Outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Run Terraform init
        run: terraform init

      - name: Run Terraform Apply
        run: terraform apply --auto-approve -var github_access_token=${{ secrets.PAT }} -var github_commit_sha=${{ steps.vars.outputs.sha_short }} -var vpc_id=${{ secrets.VPC_ID }}

      - uses: actions/upload-artifact@v4
        with:
          name: terraform.tfstate
          path: terraform.tfstate

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: create-github-runner
    steps:
      - run: echo Works!

  remove-github-runner:
    name: Remove GitHub Runner
    runs-on: ubuntu-latest
    needs: deploy
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Set Outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Run Terraform init
        run: terraform init

      - uses: actions/download-artifact@v4
        with:
          name: terraform.tfstate

      - name: Run Terraform Destroy
        run: terraform destroy --auto-approve -var github_access_token=${{ secrets.PAT }} -var github_commit_sha=${{ steps.vars.outputs.sha_short }} -var vpc_id=${{ secrets.VPC_ID }}
