name: on-main

on:
  deployment:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_VERSION: 1.7.3

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: ${{ matrix.environments }}
    concurrency:
      group: Terraform (${{ matrix.environments }})
    strategy:
      matrix:
        environments: [test]
    steps:
      - uses: actions/checkout@v3

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          prefix: TF_VAR_

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -no-color --auto-approve
