name: on-main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  liquibase-dev:
    name: Liquibase (dev)
    runs-on: self-hosted
    environment: dev
    steps:
      - run: echo Works!

      - uses: liquibase-github-actions/update@v4.27.0   
        with:
          changelogFile: test
          url: test
          password: test
          username: test
